default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  # database: myapp_development
  # username: wormer
  # password: wormer
  # host: db
  # port: 5432
  database: <%= ENV["database_name"]%>
  username: <%= ENV["database_user"]%>
  password: <%= ENV["database_password"]%>
  host: <%= ENV["database_host"]%>
  port: <%= ENV["database_port"]%>

test:
  <<: *default
  database: myapp_test
  username: wormer
  password: wormer
  host: db

production:
  <<: *default
  database: myapp_production
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: db
  pool: 5
  timeout: 5000
